### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by wistful** [wistful/SublimeAutoPEP8#48]
Logs:
autopep8.params: Namespace(aggressive=4, diff=True, exclude=[], experimental=False, files=['fake-file'], global_config='/home/developer/.config/pep8', ignore='', ignore_local_config=False, in_place=False, indent_size=4, jobs=1, line_range=None, list_fixes=False, max_line_length=79, pep8_passes=-1, recursive=False, select=['E', 'W'], verbose=2)
Traceback (most recent call last):
  File "sublautopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 140, in <lambda>
  File "sublimeautopep8lib.common in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 159, in worker
  File "sublimeautopep8lib.autopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 2864, in fix_code
  File "sublimeautopep8lib.autopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 2883, in fix_lines
  File "sublimeautopep8lib.autopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 2978, in apply_global_fixes
  File "sublimeautopep8lib.autopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 1262, in fix_w602
  File "sublimeautopep8lib.autopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 1219, in refactor
  File "sublimeautopep8lib.autopep8 in /home/developer/.config/sublime-text-3/Installed Packages/AutoPEP8.sublime-package", line 2644, in refactor_with_2to3
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "./python3.3/lib2to3/refactor.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "./python3.3/lib2to3/fixer_util.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "./python3.3/lib2to3/pygram.py", line 32, in <module>
  File "./python3.3/lib2to3/pgen2/driver.py", line 121, in load_grammar
  File "./python3.3/lib2to3/pgen2/pgen.py", line 385, in generate_grammar
  File "./python3.3/lib2to3/pgen2/pgen.py", line 15, in __init__
NotADirectoryError: [Errno 20] Not a directory: '/home/developer/sublime_text_3/python3.3.zip/lib2to3/Grammar.txt'

**Comment by wistful** [comment]
The 'lib2to3' package was removed in the scope of removing 'aggressive' option from the configuration.
