### ISSUE TITLE
Cannot find argparse

### ISSUE THREAD

**Issue by carpenterjc** [wistful/SublimeAutoPEP8#49]
AutoPEP8 is consistantly failing on sublime2 on windows. 

>>> Hit ctlshiftf8
Traceback (most recent call last):
  File ".\sublautopep8.py", line 138, in <lambda>
  File ".\sublautopep8.py", line 115, in pep8_params
  File ".\sublimeautopep8lib\autopep8.py", line 3145, in parse_args
  File ".\sublimeautopep8lib\autopep8.py", line 3078, in create_parser
ImportError: No module named argparse

Sublime is installed on a windows box with python 2.7 64 bit and python 3.6 64.
>>> sys.version
'2.6.5 (r265:79096, Mar 19 2010, 18:02:59) [MSC v.1500 64 bit (AMD64)]'

**Comment by wistful** [comment]
Thanks for reporting the issue.
Could you please provide plugin version?

**Comment by wistful** [comment]
The fix(b5ef05a1f6a5931bcea5b4a4547d88384a6c5c9d) was submitted.
The new version will be published soon.

**Comment by wistful** [comment]
The bug was fixed in v1.3.5
