### ISSUE TITLE
Python 2.6 support?

### ISSUE THREAD

**Issue by egberts** [wistful/SublimeAutoPEP8#52]
On CentOS 5.8, running `autopep8` resulted in the following output:

    $ autopep8
        Traceback (most recent call last):
      File "/usr/bin/autopep8", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
        working_set.require(__requires__)
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: pycodetype>=2.3
    $

And I do have pycodetype 2.3.1 installed.

    $ pip show pycodestyle
    Name: pycodestyle
    Version: 2.3.1
    Summary: Python style guide checker
    Home-page: https://pycodestyle.readthedocs.io/
    Author: Ian Lee
    Author-email: IanLee1521@gmail.com
    License: Expat license
    Location: /usr/lib/python2.6/site-packages
    Requires:

Please advise.

TIA.

**Comment by wistful** [comment]
The plugin doesn't use system autopep8 module.
Could you provide a traceback or any error messages from from Sublime Text?
