### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by lampda** [wistful/SublimeAutoPEP8#61]
Hi there,

I got this error, **AttributeError: 'list' object has no attribute 'split'**.

<pre>
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/AutoPEP8.sublime-package/sublautopep8.py", line 175, in <lambda>
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/AutoPEP8.sublime-package/sublautopep8.py", line 137, in pep8_params
AttributeError: 'list' object has no attribute 'split'
</pre>

What is wrong with my installation or this package?

Cheers,

**Comment by ac130kz** [comment]
I got the same error (Ubuntu 18.04), seems like either the package is broken, or it somehow interacts with the system-wide Python installation, which can explain the AttributeError.
